version: "2"
services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: tests/app/docker/Dockerfile
    command: ["sleep", "infinity"]
    volumes:
      - ./:/app
      - /tests/app/runtime/composer:/root/.composer
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
      TERM: xterm-256color
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 15672:5672
